// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHPgvZuuBwhzeRixUe8NyKM4v3Ic_WIQo',
    appId: '1:650861268769:web:f0083eb277f2182e31b860',
    messagingSenderId: '650861268769',
    projectId: 'litera2-c50c9',
    authDomain: 'litera2-c50c9.firebaseapp.com',
    storageBucket: 'litera2-c50c9.firebasestorage.app',
    measurementId: 'G-ZTNJMMV806',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcaB7U4ovifAaihItnBc_Cu8yGgPQFDWA',
    appId: '1:650861268769:android:33750c8a86cce45831b860',
    messagingSenderId: '650861268769',
    projectId: 'litera2-c50c9',
    storageBucket: 'litera2-c50c9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnpXlvI77Ss57yMBT2AN9w24mbbDGrKuc',
    appId: '1:650861268769:ios:fedc00280a9219ee31b860',
    messagingSenderId: '650861268769',
    projectId: 'litera2-c50c9',
    storageBucket: 'litera2-c50c9.firebasestorage.app',
    iosBundleId: 'com.example.litera2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAnpXlvI77Ss57yMBT2AN9w24mbbDGrKuc',
    appId: '1:650861268769:ios:fedc00280a9219ee31b860',
    messagingSenderId: '650861268769',
    projectId: 'litera2-c50c9',
    storageBucket: 'litera2-c50c9.firebasestorage.app',
    iosBundleId: 'com.example.litera2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAHPgvZuuBwhzeRixUe8NyKM4v3Ic_WIQo',
    appId: '1:650861268769:web:5f4b4da5b25f1e3831b860',
    messagingSenderId: '650861268769',
    projectId: 'litera2-c50c9',
    authDomain: 'litera2-c50c9.firebaseapp.com',
    storageBucket: 'litera2-c50c9.firebasestorage.app',
    measurementId: 'G-6Z1MRFP3F8',
  );
}
